if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "INPUT and OUTPUT are required")
endif()

file(READ "${INPUT}" bytes HEX)
string(REGEX MATCHALL ".." byte_list "${bytes}")
file(WRITE "${OUTPUT}" "/* Generated binary resource. */\n")
file(APPEND "${OUTPUT}" "const unsigned char ortos_cursor_resource[] = {\n")
set(column 0)
foreach(byte IN LISTS byte_list)
    file(APPEND "${OUTPUT}" "0x${byte},")
    math(EXPR column "${column} + 1")
    if(column EQUAL 16)
        file(APPEND "${OUTPUT}" "\n")
        set(column 0)
    endif()
endforeach()
file(APPEND "${OUTPUT}" "\n};\n")
file(APPEND "${OUTPUT}" "const unsigned long ortos_cursor_resource_size = sizeof(ortos_cursor_resource);\n")